#spring: 
#datasource:
#driverClassName: com.mysql.jdbd.Driver
#url: jdbc:mysql://localhost:3306/student
#username: root
#password: harenash
#
#jpa:
#hibernate.ddl-auto: update
#generate-ddl: true
#show-sql: true
#
#server:
#port: 8081
#spring:
#  cloud:
#    config:
#      uri: http://localhost:9196